import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";

const pingFang = LocalFont(
  {
    src: "./fonts/PingFang Regular.ttf",
    variable: "--pingfang-regular",
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={pingFang.variable}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
